// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALSkSJUi02aLfb0t_BK4HAU_E5UEK8x7Y',
    appId: '1:757223062516:web:5249b42553bfc4290017a1',
    messagingSenderId: '757223062516',
    projectId: 'uasflutter-cf800',
    authDomain: 'uasflutter-cf800.firebaseapp.com',
    storageBucket: 'uasflutter-cf800.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzukQMFmw-xfD_cIdxvSpEqay5mXbADk4',
    appId: '1:757223062516:android:393ac42470c4ce5b0017a1',
    messagingSenderId: '757223062516',
    projectId: 'uasflutter-cf800',
    storageBucket: 'uasflutter-cf800.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTAJVwN1jnQHmZQZvSIv-udE7ePBei7tA',
    appId: '1:757223062516:ios:ec0d3cc1eb7f2d380017a1',
    messagingSenderId: '757223062516',
    projectId: 'uasflutter-cf800',
    storageBucket: 'uasflutter-cf800.appspot.com',
    iosClientId: '757223062516-gfb8s34nao54l264h3c28k3qfrv1k3ar.apps.googleusercontent.com',
    iosBundleId: 'com.example.c1419000301',
  );
}
